export const mock = {
  product: {
    header: [
      {
        productName: 'Yaki Be-fun',
        brandName: 'Kenmin Foods',
        primarySize: '2.29 oz',
        secondarySize: '65g',
        thirdSize: '',
        fullSizeTextDescription: 'NET WT. 2.29 OZ ( 65g )',
        count: '',
        primarySizeValue: 2.29,
        primarySizeText: '2.29 OUNCE',
        primarySizeUOM: 'OUNCE',
        secondarySizeValue: 65,
        secondarySizeText: '65GRAM',
        secondarySizeUOM: 'GRAM',
      },
    ],
    physical: [
      {
        upc12: '50009312013',
      },
    ],
    attributes: {
      containAndNotContain: [
        {
          claim: 'additives',
          mentioned: 'false',
          reason: '',
          source: '',
          containOrNot: '',
          contain: 'false',
          notContain: 'true',
        },
        {
          claim: 'added colors',
          mentioned: 'false',
          reason: '',
          source: '',
          containOrNot: '',
          contain: 'false',
          notContain: 'true',
        },
        {
          claim: 'artificial additives',
          mentioned: 'false',
          reason: '',
          source: '',
          containOrNot: '',
          contain: 'false',
          notContain: 'true',
        },
        {
          claim: 'chemical additives',
          mentioned: 'false',
          reason: '',
          source: '',
          containOrNot: '',
          contain: 'false',
          notContain: 'true',
        },
        {
          claim: 'synthetic additives',
          mentioned: 'false',
          reason: '',
          source: '',
          containOrNot: '',
          contain: 'false',
          notContain: 'true',
        },
        {
          claim: 'natural additives',
          mentioned: 'false',
          reason: '',
          source: '',
          containOrNot: '',
          contain: 'false',
          notContain: 'true',
        },
        {
          claim: 'artificial colors',
          mentioned: 'false',
          reason: '',
          source: '',
          containOrNot: '',
          contain: 'false',
          notContain: 'true',
        },
        {
          claim: 'chemical colors',
          mentioned: 'false',
          reason: '',
          source: '',
          containOrNot: '',
          contain: 'false',
          notContain: 'true',
        },
        {
          claim: 'synthetic colors',
          mentioned: 'false',
          reason: '',
          source: '',
          containOrNot: '',
          contain: 'false',
          notContain: 'true',
        },
        {
          claim: 'natural colors',
          mentioned: 'false',
          reason: '',
          source: '',
          containOrNot: '',
          contain: 'false',
          notContain: 'true',
        },
        {
          claim: 'dyes',
          mentioned: 'false',
          reason: '',
          source: '',
          containOrNot: '',
          contain: 'false',
          notContain: 'true',
        },
        {
          claim: 'added dyes',
          mentioned: 'false',
          reason: '',
          source: '',
          containOrNot: '',
          contain: 'false',
          notContain: 'true',
        },
        {
          claim: 'artificial dyes',
          mentioned: 'false',
          reason: '',
          source: '',
          containOrNot: '',
          contain: 'false',
          notContain: 'true',
        },
        {
          claim: 'chemical dyes',
          mentioned: 'false',
          reason: '',
          source: '',
          containOrNot: '',
          contain: 'false',
          notContain: 'true',
        },
        {
          claim: 'synthetic dyes',
          mentioned: 'false',
          reason: '',
          source: '',
          containOrNot: '',
          contain: 'false',
          notContain: 'true',
        },
        {
          claim: 'natural dyes',
          mentioned: 'false',
          reason: '',
          source: '',
          containOrNot: '',
          contain: 'false',
          notContain: 'true',
        },
        {
          claim: 'added flavors',
          mentioned: 'false',
          reason: '',
          source: '',
          containOrNot: '',
          contain: 'false',
          notContain: 'true',
        },
        {
          claim: 'artificial flavors',
          mentioned: 'false',
          reason: '',
          source: '',
          containOrNot: '',
          contain: 'false',
          notContain: 'true',
        },
        {
          claim: 'chemical flavors',
          mentioned: 'false',
          reason: '',
          source: '',
          containOrNot: '',
          contain: 'false',
          notContain: 'true',
        },
        {
          claim: 'synthetic flavors',
          mentioned: 'false',
          reason: '',
          source: '',
          containOrNot: '',
          contain: 'false',
          notContain: 'true',
        },
        {
          claim: 'natural flavors',
          mentioned: 'false',
          reason: '',
          source: '',
          containOrNot: '',
          contain: 'false',
          notContain: 'true',
        },
        {
          claim: 'naturally flavored',
          mentioned: 'false',
          reason: '',
          source: '',
          containOrNot: '',
          contain: 'false',
          notContain: 'true',
        },
        {
          claim: 'added fragrances',
          mentioned: 'false',
          reason: '',
          source: '',
          containOrNot: '',
          contain: 'false',
          notContain: 'true',
        },
        {
          claim: 'artificial fragrance',
          mentioned: 'false',
          reason: '',
          source: '',
          containOrNot: '',
          contain: 'false',
          notContain: 'true',
        },
        {
          claim: 'chemical fragrances',
          mentioned: 'false',
          reason: '',
          source: '',
          containOrNot: '',
          contain: 'false',
          notContain: 'true',
        },
        {
          claim: 'synthetic fragrance',
          mentioned: 'false',
          reason: '',
          source: '',
          containOrNot: '',
          contain: 'false',
          notContain: 'true',
        },
        {
          claim: 'preservatives',
          mentioned: 'false',
          reason: '',
          source: '',
          containOrNot: '',
          contain: 'false',
          notContain: 'true',
        },
        {
          claim: 'added preservatives',
          mentioned: 'false',
          reason: '',
          source: '',
          containOrNot: '',
          contain: 'false',
          notContain: 'true',
        },
        {
          claim: 'artificial preservatives',
          mentioned: 'false',
          reason: '',
          source: '',
          containOrNot: '',
          contain: 'false',
          notContain: 'true',
        },
        {
          claim: 'chemical preservatives',
          mentioned: 'false',
          reason: '',
          source: '',
          containOrNot: '',
          contain: 'false',
          notContain: 'true',
        },
        {
          claim: 'synthetic preservatives',
          mentioned: 'false',
          reason: '',
          source: '',
          containOrNot: '',
          contain: 'false',
          notContain: 'true',
        },
        {
          claim: 'natural preservatives',
          mentioned: 'false',
          reason: '',
          source: '',
          containOrNot: '',
          contain: 'false',
          notContain: 'true',
        },
        {
          claim: 'artificial ingredients',
          mentioned: 'false',
          reason: '',
          source: '',
          containOrNot: '',
          contain: 'false',
          notContain: 'true',
        },
        {
          claim: 'chemical ingredients',
          mentioned: 'false',
          reason: '',
          source: '',
          containOrNot: '',
          contain: 'false',
          notContain: 'true',
        },
        {
          claim: 'synthetic ingredients',
          mentioned: 'false',
          reason: '',
          source: '',
          containOrNot: '',
          contain: 'false',
          notContain: 'true',
        },
        {
          claim: 'natural ingredients',
          mentioned: 'false',
          reason: '',
          source: '',
          containOrNot: '',
          contain: 'false',
          notContain: 'true',
        },
        {
          claim: 'animal ingredients',
          mentioned: 'false',
          reason: '',
          source: '',
          containOrNot: '',
          contain: 'false',
          notContain: 'true',
        },
        {
          claim: 'chemical sunscreens',
          mentioned: 'false',
          reason: '',
          source: '',
          containOrNot: '',
          contain: 'false',
          notContain: 'true',
        },
        {
          claim: 'animal by-products',
          mentioned: 'false',
          reason: '',
          source: '',
          containOrNot: '',
          contain: 'false',
          notContain: 'true',
        },
        {
          claim: 'animal derivatives',
          mentioned: 'false',
          reason: '',
          source: '',
          containOrNot: '',
          contain: 'false',
          notContain: 'true',
        },
        {
          claim: 'animal products',
          mentioned: 'false',
          reason: '',
          source: '',
          containOrNot: '',
          contain: 'false',
          notContain: 'true',
        },
        {
          claim: 'animal rennet',
          mentioned: 'false',
          reason: '',
          source: '',
          containOrNot: '',
          contain: 'false',
          notContain: 'true',
        },
        {
          claim: 'antibiotics',
          mentioned: 'false',
          reason: '',
          source: '',
          containOrNot: '',
          contain: 'false',
          notContain: 'true',
        },
        {
          claim: 'added antibiotics',
          mentioned: 'false',
          reason: '',
          source: '',
          containOrNot: '',
          contain: 'false',
          notContain: 'true',
        },
        {
          claim: 'synthetics',
          mentioned: 'false',
          reason: '',
          source: '',
          containOrNot: '',
          contain: 'false',
          notContain: 'true',
        },
        {
          claim: 'chemicals',
          mentioned: 'false',
          reason: '',
          source: '',
          containOrNot: '',
          contain: 'false',
          notContain: 'true',
        },
        {
          claim: 'hormones',
          mentioned: 'false',
          reason: '',
          source: '',
          containOrNot: '',
          contain: 'false',
          notContain: 'true',
        },
        {
          claim: 'added hormones',
          mentioned: 'false',
          reason: '',
          source: '',
          containOrNot: '',
          contain: 'false',
          notContain: 'true',
        },
        {
          claim: 'nitrates/nitrites',
          mentioned: 'false',
          reason: '',
          source: '',
          containOrNot: '',
          contain: 'false',
          notContain: 'true',
        },
        {
          claim: 'added nitrates',
          mentioned: 'false',
          reason: '',
          source: '',
          containOrNot: '',
          contain: 'false',
          notContain: 'true',
        },
        {
          claim: 'added nitrites',
          mentioned: 'false',
          reason: '',
          source: '',
          containOrNot: '',
          contain: 'false',
          notContain: 'true',
        },
        {
          claim: 'yeast',
          mentioned: 'false',
          reason: '',
          source: '',
          containOrNot: '',
          contain: 'false',
          notContain: 'true',
        },
        {
          claim: 'active yeast',
          mentioned: 'false',
          reason: '',
          source: '',
          containOrNot: '',
          contain: 'false',
          notContain: 'true',
        },
        {
          claim: 'allergen',
          mentioned: 'true',
          contain: 'no',
          notContain: 'yes',
          source: 'marketing text on product',
          reason: 'Text on the front of the package states "Gluten-Free"',
        },
        {
          claim: 'gluten',
          mentioned: 'true',
          contain: 'no',
          notContain: 'yes',
          source: 'marketing text on product',
          reason: 'Text on the front of the package states "Gluten-Free"',
        },
        {
          claim: 'cholesterol',
          mentioned: 'true',
          contain: 'yes',
          notContain: 'no',
          source: 'nutrition fact',
          reason:
            'The nutrition fact states that the product contains 0mg of cholesterol.',
        },
        {
          claim: 'sulfites / sulphites',
          mentioned: 'true',
          contain: 'yes',
          notContain: 'no',
          source: 'ingredient list',
          reason:
            'The ingredient list states that the product contains sulfites.',
        },
      ],
      fatClaims: [
        {
          claim: 'trans fat free',
          isClaimed: 'true',
          source: 'nutrition fact',
          reason: 'The nutrition facts state that there is 0g of trans fat.',
        },
      ],
      nonCertificateClaims: [
        {
          claim: 'not fried',
          isClaimed: 'true',
          source: 'marketing text on product',
          reason:
            'The product description states that it is "SEASONED & NON-FRIED RICE NOODLE"',
        },
      ],
      calorieClaims: [],
      saltClaims: [
        {
          claim: 'low sodium',
          isClaimed: 'false',
          source: '',
        },
        {
          claim: 'no salt',
          isClaimed: 'false',
          source: '',
        },
        {
          claim: 'no salt added',
          isClaimed: 'false',
          source: '',
        },
        {
          claim: 'reduced sodium',
          isClaimed: 'false',
          source: '',
        },
        {
          claim: 'salt free',
          isClaimed: 'false',
          source: '',
        },
        {
          claim: 'sodium free',
          isClaimed: 'false',
          source: '',
        },
        {
          claim: 'unsalted',
          isClaimed: 'false',
          source: '',
        },
        {
          claim: 'very low sodium',
          isClaimed: 'false',
          source: '',
        },
      ],
      sugarClaims: [
        {
          claim: 'no contain saccharin',
          isClaimed: 'true',
          source: 'ingredient list',
          reason:
            'The ingredient list states that the product does not contain saccharin.',
        },
      ],
      validated_notContain: ['allergen'],
      validated_nonCertificateClaims: ['not fried'],
    },
    ingredients: [
      {
        isProductSupplement: 'false',
        ingredientStatement:
          "RICE, STARCH ( TAPIOCA , POTATO , CORN ) , SOY SAUCE ( WATER , SOYBEANS , WHEAT , SALT ) , SALT , KELP EXTRACT , MONOSODIUM GLUTAMATE , FISH EXTRACT ( MALTODEXTRIN , BONITO EXTRACT , SALT , FISH EXTRACT POWDER ( EASTERN LITTLE TUNA , FRIGATE MACKEREL , SKIPJACK TUNA ) , YEAST EXTRACT ) , SUGAR , GINGER PASTE , MONO - AND DIGLYCERIDES OF FATTY ACIDS , SODIUM METAPHOSPHATE , SODIUM TRIPOLYPHOSPHATE , TETRASODIUM PYROPHOSPHATE , CARBOXYMETHYL CELLULOSE , GARLIC POWDER , ONION POWDER , DISODIUM 5 ' - RIBONUCLEOTIDE , CARAMEL COLOR , YEAST EXTRACT , PEPPER , SUCROSE FATTY ACID ESTERS , COLOR ( RIBOFLAVIN ) , ROSEMARY EXTRACT .",
      },
    ],
    allergens: [
      {
        containStatement:
          'Contains: Soybeans, Sulfites, Fish and Tree Nuts (Coconut)',
        containList: 'Soybeans, Sulfites, Fish, Tree Nuts',
        notContainStatement: '',
        notContainList: '',
        containOnEquipmentStatement: '',
        containOnEquipmentList: '',
      },
    ],
    instructions: [
      {
        storageInstruction: '',
        cookingInstruction:
          'Heat frying pan and add one and half table spoon of cooking oil. Lay down pork belly strips and layer with Yaki - Befun noodles , and ( vegetables in this particular order .<br>Add 6.7 ounces of water , seal with a lid and heat on high heat for 3 mins .<br>After 3 minutes , remove the lid and lightly mix the ingredients around and let the remaining water evaporate . Serve hot .',
        usageInstruction: '',
        usageTimeInstruction: '',
        otherInstructions:
          '* 2 servings add 11.5 ounces of water .<br>* sesame oil can be added for extra flavor',
      },
    ],
    marketing: [
      {
        haveQrCode: 'false',
        instagram: 'false',
        pinterest: 'false',
        youtube: 'false',
        facebook: 'false',
        twitter: 'false',
        socialMediaList: '',
        website: 'http://www.kenmin.co.jp',
        socialMediaText: '',
        enlargedToShow: 'false',
      },
    ],
    supplyChain: [
      {
        countryOfOrigin: 'Thailand',
        manufacturerName: 'KENMIN FOODS CO., LTD.',
        manufacturerDate: '',
        manufacturerPhoneNumber: '',
        manufacturerStreetAddress: '',
        manufacturerCity: '',
        manufacturerState: '',
        manufactureZipCode: '',
      },
    ],
    factPanels: [
      {
        title: '[1]',
        servingInfo: {
          servingPerContainer: '',
          servingSize: '1 pack',
          equivalentServingSize: '(65g)',
          amountPerServingName: '',
          calories: '230',
        },
        nutritionFacts: [
          {
            nutrientName: 'Calories',
            parenthesesDescriptor: null,
            amountPerServing: '230',
            amountPerServingDescriptor: '',
            dailyValue: '',
            blendIngredients: null,
            validated_nutrientName: 'CALORIES',
            amount: 230,
            uom: null,
          },
          {
            nutrientName: 'Total Fat',
            parenthesesDescriptor: null,
            amountPerServing: '1g',
            amountPerServingDescriptor: '',
            dailyValue: '1%',
            blendIngredients: null,
            validated_nutrientName: 'TOTAL FAT',
            amount: 1,
            uom: 'GRAM',
            percent: '1',
            indicator: null,
          },
          {
            nutrientName: 'Saturated Fat',
            parenthesesDescriptor: null,
            amountPerServing: '0.5g',
            amountPerServingDescriptor: '',
            dailyValue: '3%',
            blendIngredients: null,
            validated_nutrientName: 'SATURATED FAT',
            amount: 0.5,
            uom: 'GRAM',
            percent: '3',
            indicator: null,
          },
          {
            nutrientName: 'Trans Fat',
            parenthesesDescriptor: null,
            amountPerServing: '0g',
            amountPerServingDescriptor: '',
            dailyValue: '0%',
            blendIngredients: null,
            validated_nutrientName: 'TRANS FAT',
            amount: 0,
            uom: 'GRAM',
            percent: '0',
            indicator: null,
          },
          {
            nutrientName: 'Cholesterol',
            parenthesesDescriptor: null,
            amountPerServing: '0mg',
            amountPerServingDescriptor: '',
            dailyValue: '0%',
            blendIngredients: null,
            validated_nutrientName: 'CHOLESTEROL',
            amount: 0,
            uom: 'MILLIGRAM',
            percent: '0',
            indicator: null,
          },
          {
            nutrientName: 'Sodium',
            parenthesesDescriptor: null,
            amountPerServing: '1190mg',
            amountPerServingDescriptor: '',
            dailyValue: '52%',
            blendIngredients: null,
            validated_nutrientName: 'SODIUM',
            amount: 1190,
            uom: 'MILLIGRAM',
            percent: '52',
            indicator: null,
          },
          {
            nutrientName: 'Total Carbohydrate',
            parenthesesDescriptor: null,
            amountPerServing: '51g',
            amountPerServingDescriptor: '',
            dailyValue: '19%',
            blendIngredients: null,
            validated_nutrientName: 'TOTAL CARBOHYDRATE',
            amount: 51,
            uom: 'GRAM',
            percent: '19',
            indicator: null,
          },
          {
            nutrientName: 'Dietary Fiber',
            parenthesesDescriptor: null,
            amountPerServing: '1g',
            amountPerServingDescriptor: '',
            dailyValue: '4%',
            blendIngredients: null,
            validated_nutrientName: 'DIETARY FIBER',
            amount: 1,
            uom: 'GRAM',
            percent: '4',
            indicator: null,
          },
          {
            nutrientName: 'Total Sugars',
            parenthesesDescriptor: null,
            amountPerServing: '0g',
            amountPerServingDescriptor: '',
            dailyValue: '0%',
            blendIngredients: null,
            validated_nutrientName: 'TOTAL SUGARS',
            amount: 0,
            uom: 'GRAM',
            percent: '0',
            indicator: null,
          },
          {
            nutrientName: 'Added Sugars',
            parenthesesDescriptor: null,
            amountPerServing: '0g',
            amountPerServingDescriptor: '',
            dailyValue: '0%',
            blendIngredients: null,
            validated_nutrientName: 'ADDED SUGARS',
            amount: 0,
            uom: 'GRAM',
            percent: '0',
            indicator: null,
          },
          {
            nutrientName: 'Protein',
            parenthesesDescriptor: null,
            amountPerServing: '4g',
            amountPerServingDescriptor: '',
            dailyValue: '0%',
            blendIngredients: null,
            validated_nutrientName: 'PROTEIN',
            amount: 4,
            uom: 'GRAM',
            percent: '0',
            indicator: null,
          },
          {
            nutrientName: 'Vitamin D',
            parenthesesDescriptor: null,
            amountPerServing: '0mcg',
            amountPerServingDescriptor: '',
            dailyValue: '2%',
            blendIngredients: null,
            validated_nutrientName: 'VITAMIN D',
            amount: 0,
            uom: 'MICROGRAM',
            percent: '2',
            indicator: null,
          },
          {
            nutrientName: 'Calcium',
            parenthesesDescriptor: null,
            amountPerServing: '20mg',
            amountPerServingDescriptor: '',
            dailyValue: '2%',
            blendIngredients: null,
            validated_nutrientName: 'CALCIUM',
            amount: 20,
            uom: 'MILLIGRAM',
            percent: '2',
            indicator: null,
          },
          {
            nutrientName: 'Iron',
            parenthesesDescriptor: null,
            amountPerServing: '1 mg',
            amountPerServingDescriptor: '',
            dailyValue: '6%',
            blendIngredients: null,
            validated_nutrientName: 'IRON',
            amount: 1,
            uom: 'MILLIGRAM',
            percent: '6',
            indicator: null,
          },
          {
            nutrientName: 'Potassium',
            parenthesesDescriptor: null,
            amountPerServing: '120mg',
            amountPerServingDescriptor: '',
            dailyValue: '2%',
            blendIngredients: null,
            validated_nutrientName: 'POTASSIUM',
            amount: 120,
            uom: 'MILLIGRAM',
            percent: '2',
            indicator: null,
          },
        ],
        footnotes: [
          {
            footnoteContent:
              '* The % Daily Value (DV) tells you how much a nutrient in a serving of food contributes to a daily diet. 2,000 calories a day is used for general nutrition advice.',
            footnoteContentEnglish:
              '* The % Daily Value (DV) tells you how much a nutrient in a serving of food contributes to a daily diet. 2,000 calories a day is used for general nutrition advice.',
          },
        ],
        markdown:
          'NUTRITION_FACT_TABLE [1]\n| Nutrient Name | nutrient name descriptor | Amount per Serving | parenthetical statement about amount per serving | % Daily Value and footnote symbol if avail | blend ingredients (if nutrient is a blend/mix) (nullable) | \n| ------- | -------- | -------- | -------- | -------- | -------- | \n| Calories | | 230 | | | |\n| Total Fat | | 1g | | 1% | |\n| Saturated Fat | | 0.5g | | 3% | |\n| Trans Fat | | 0g | | 0% | |\n| Cholesterol | | 0mg | | 0% | |\n| Sodium | | 1190mg | | 52% | |\n| Total Carbohydrate | | 51g | | 19% | |\n| Dietary Fiber | | 1g | | 4% | |\n| Total Sugars | | 0g | | 0% | |\n| Added Sugars | | 0g | | 0% | |\n| Protein | | 4g | | 0% | |\n| Vitamin D | | 0mcg | | 2% | |\n| Calcium | | 20mg | | 2% | |\n| Iron | | 1 mg | | 6% | |\n| Potassium | | 120mg | | 2% | |\n\nHEADER_TABLE [1]\n| Serving Per Container | Serving Size | Equivalent Serving Size | Amount Per Serving name | Calories |\n| ------- | -------- | -------- | -------- | -------- |\n|  | 1 pack | (65g) |  | 230 |\n\nFOOTNOTE_TABLE [1]\n| footnote content at bottom of nutrition fact | footnote content in english only (include footnote symbol if avail) |\n| ------- | -------- |\n| * The % Daily Value (DV) tells you how much a nutrient in a serving of food contributes to a daily diet. 2,000 calories a day is used for general nutrition advice. | * The % Daily Value (DV) tells you how much a nutrient in a serving of food contributes to a daily diet. 2,000 calories a day is used for general nutrition advice. |\n\nDEBUG_TABLE\n| question (question from debug list below) | gemini answer |\n| ------- | -------- |\n| gemini answer me how many nutrition fact tables from provided images? are they the same one ? | There is 1 nutrition fact table in these images.  |\n| are they in dual-column format? and tell me why? tell me why you create only one nutrition fact table for dual-column nutrition fact panel format ? remember dual-column label format must be recorded as multiple nutrition fact markdown tables. | This nutrition fact table is not in a dual-column format. Although the nutrients are displayed in two columns to save space, this does not make it a dual-column format. Dual-column formats typically have two sets of "% Daily Value" columns for different serving sizes or age groups.  |\n',
        debugTable: [
          {
            question: '-------',
            geminiAnswer: '--------',
          },
          {
            question:
              'gemini answer me how many nutrition fact tables from provided images? are they the same one ?',
            geminiAnswer: 'There is 1 nutrition fact table in these images.',
          },
          {
            question:
              'are they in dual-column format? and tell me why? tell me why you create only one nutrition fact table for dual-column nutrition fact panel format ? remember dual-column label format must be recorded as multiple nutrition fact markdown tables.',
            geminiAnswer:
              'This nutrition fact table is not in a dual-column format. Although the nutrients are displayed in two columns to save space, this does not make it a dual-column format. Dual-column formats typically have two sets of "% Daily Value" columns for different serving sizes or age groups.',
          },
        ],
      },
    ],
    nutMark:
      'NUTRITION_FACT_TABLE [1]\n| Nutrient Name | nutrient name descriptor | Amount per Serving | parenthetical statement about amount per serving | % Daily Value and footnote symbol if avail | blend ingredients (if nutrient is a blend/mix) (nullable) | \n| ------- | -------- | -------- | -------- | -------- | -------- | \n| Calories | | 230 | | | |\n| Total Fat | | 1g | | 1% | |\n| Saturated Fat | | 0.5g | | 3% | |\n| Trans Fat | | 0g | | 0% | |\n| Cholesterol | | 0mg | | 0% | |\n| Sodium | | 1190mg | | 52% | |\n| Total Carbohydrate | | 51g | | 19% | |\n| Dietary Fiber | | 1g | | 4% | |\n| Total Sugars | | 0g | | 0% | |\n| Added Sugars | | 0g | | 0% | |\n| Protein | | 4g | | 0% | |\n| Vitamin D | | 0mcg | | 2% | |\n| Calcium | | 20mg | | 2% | |\n| Iron | | 1 mg | | 6% | |\n| Potassium | | 120mg | | 2% | |\n\nHEADER_TABLE [1]\n| Serving Per Container | Serving Size | Equivalent Serving Size | Amount Per Serving name | Calories |\n| ------- | -------- | -------- | -------- | -------- |\n|  | 1 pack | (65g) |  | 230 |\n\nFOOTNOTE_TABLE [1]\n| footnote content at bottom of nutrition fact | footnote content in english only (include footnote symbol if avail) |\n| ------- | -------- |\n| * The % Daily Value (DV) tells you how much a nutrient in a serving of food contributes to a daily diet. 2,000 calories a day is used for general nutrition advice. | * The % Daily Value (DV) tells you how much a nutrient in a serving of food contributes to a daily diet. 2,000 calories a day is used for general nutrition advice. |\n\nDEBUG_TABLE\n| question (question from debug list below) | gemini answer |\n| ------- | -------- |\n| gemini answer me how many nutrition fact tables from provided images? are they the same one ? | There is 1 nutrition fact table in these images.  |\n| are they in dual-column format? and tell me why? tell me why you create only one nutrition fact table for dual-column nutrition fact panel format ? remember dual-column label format must be recorded as multiple nutrition fact markdown tables. | This nutrition fact table is not in a dual-column format. Although the nutrients are displayed in two columns to save space, this does not make it a dual-column format. Dual-column formats typically have two sets of "% Daily Value" columns for different serving sizes or age groups.  |\n',
    allMark:
      '## FIRST_EXTRA_CLAIM_TABLE\n| extra item | is mentioned on product ?  | mentioned on which text on product ? | do you know it through which source of info ? (answer are  "ingredient list"/ "marketing text on product"/ "nutrition fact"/ "others") (answer could be multiple string since the info can appeared in multiple sources) | product contain it ? (answer is yes/no) |\n| ------- | -------- | -------- | -------- | -------- |\n| additives | false |  |  |  |\n| added colors | false |  |  |  |\n| artificial additives | false |  |  |  |\n| chemical additives | false |  |  |  |\n| synthetic additives | false |  |  |  |\n| natural additives | false |  |  |  |\n| artificial colors | false |  |  |  |\n| chemical colors | false |  |  |  |\n| synthetic colors | false |  |  |  |\n| natural colors | false |  |  |  |\n| dyes | false |  |  |  |\n| added dyes | false |  |  |  |\n| artificial dyes | false |  |  |  |\n| chemical dyes | false |  |  |  |\n| synthetic dyes | false |  |  |  |\n| natural dyes | false |  |  |  |\n| added flavors | false |  |  |  |\n| artificial flavors | false |  |  |  |\n| chemical flavors | false |  |  |  |\n| synthetic flavors | false |  |  |  |\n| natural flavors | false |  |  |  |\n| naturally flavored | false |  |  |  |\n| added fragrances | false |  |  |  |\n| artificial fragrance | false |  |  |  |\n| chemical fragrances | false |  |  |  |\n| synthetic fragrance | false |  |  |  |\n| preservatives | false |  |  |  |\n| added preservatives | false |  |  |  |\n| artificial preservatives | false |  |  |  |\n| chemical preservatives | false |  |  |  |\n| synthetic preservatives | false |  |  |  |\n| natural preservatives | false |  |  |  |\n| artificial ingredients | false |  |  |  |\n| chemical ingredients | false |  |  |  |\n| synthetic ingredients | false |  |  |  |\n| natural ingredients | false |  |  |  |\n| animal ingredients | false |  |  |  |\n| chemical sunscreens | false |  |  |  |\n| animal by-products | false |  |  |  |\n| animal derivatives | false |  |  |  |\n| animal products | false |  |  |  |\n| animal rennet | false |  |  |  |\n| antibiotics | false |  |  |  |\n| added antibiotics | false |  |  |  |\n| synthetics | false |  |  |  |\n| chemicals | false |  |  |  |\n| hormones | false |  |  |  |\n| added hormones | false |  |  |  |\n| nitrates/nitrites | false |  |  |  |\n| added nitrates | false |  |  |  |\n| added nitrites | false |  |  |  |\n| yeast | false |  |  |  |\n| active yeast | false |  |  |  |\n\n## SECOND_EXTRA_CLAIM_TABLE\n| extra item |  item explicitly and directly state in a text on product  without implying from other text? (answer is true/false/unknown) | Does the product explicitly state contain it ? (answer is yes/no) |  Does the product explicitly state to not contain it ? (answer is yes/no)  |  do you know it through which info ? (answer are  "ingredient list"/ "marketing text on product"/ "nutrition fact"/ "allergen contain statement"/ "others") (answer could be multiple string since the info can appeared in multiple sources) | how do you know that ? and give me you explain (answer in string) |\n| ------- | -------- | ------- | ------- | -------- | -------- |\n| allergen | true | no | yes | marketing text on product | Text on the front of the package states "Gluten-Free" |\n| gluten | true | no | yes | marketing text on product | Text on the front of the package states "Gluten-Free" |\n| cholesterol | true | yes | no | nutrition fact | The nutrition fact states that the product contains 0mg of cholesterol. |\n\n## THIRD_EXTRA_CLAIM_TABLE\n| extra item |  item explicitly and directly state in a text on product  without implying from other text? (answer is true/false/unknown) | Does the product explicitly state contain it ? (answer is yes/no) |  Does the product explicitly state to not contain it ? (answer is yes/no)  |  do you know it through which info ? (answer are  "ingredient list"/ "marketing text on product"/ "nutrition fact"/ "others") (answer could be multiple string since the info can appeared in multiple sources) | how do you know that ? and give me you explain (answer in string) | do match exact text on product ? (answer is yes/no) |\n| ------- | -------- | ------- | ------- | -------- | -------- | -------- |\n| sulfites / sulphites | true | yes | no | ingredient list | The ingredient list states that the product contains sulfites. | yes |\n\n## SUGAR_CLAIM_TABLE\n| sugar claim | does product claim that sugar claim? (answer are true/false/unknown) (unknown when not mentioned) | do you know it through which info ? (answer are "ingredient list"/ "nutrition fact"/ "marketing text on product"/ "others") (answer could be multiple string from many sources) (answer could be multiple string from many sources)| how do you know that ? and give me you explain (answer in string) |\n| ------- | -------- | -------- | -------- |\n| no contain saccharin | true | ingredient list | The ingredient list states that the product does not contain saccharin. |\n\n## FAT_CLAIM_TABLE\n| fat claim | does product claim that fat claim? (answer are true/false/unknown) (unknown when not mentioned) | do you know it through which info ? (answer are "ingredient list"/ "nutrition fact"/ "marketing text on product"/ "others") (answer could be multiple string from many sources) | how do you know that ? and give me you explain (answer in string) |\n| ------- | -------- | -------- | -------- |\n| trans fat free | true | nutrition fact | The nutrition facts state that there is 0g of trans fat. |\n\n## OTHER_CLAIM_TABLE\n| other claim | does product explicitly claim this claim? (answer are true/false/unknown) (unknown when not mentioned) | do you know it through which info ? (answer are "ingredient list"/ "nutrition fact"/ "marketing text on product"/ "others") (answer could be multiple string from many sources) | how do you know that ? and give me you explain (answer in string) |\n| ------- | -------- | -------- | -------- |\n| not fried | true | marketing text on product | The product description states that it is "SEASONED & NON-FRIED RICE NOODLE" |\n\n## CALORIE_CLAIM_TABLE\n| calorie claim | does product explicitly claim the calorie claim? (answer are true/false/unknown) (unknown when not mentioned) | do you know it through which info ? (answer are "ingredient list"/ "nutrition fact"/ "marketing text on product"/ "others") (answer could be multiple string from many sources) |\n| ------- | -------- | -------- |\n\n## SALT_CLAIM_TABLE\n| salt claim | does product explicitly claim this claim? (answer are true/false/unknown) (unknown when not mentioned) | do you know it through which info ? (answer are "ingredient list"/ "nutrition fact"/ "marketing text on product"/ "others") (answer could be multiple string from many sources) |\n| lightly salted | false |  |\n| low sodium | false |  |\n| no salt | false |  |\n| no salt added | false |  |\n| reduced sodium | false |  |\n| salt free | false |  |\n| sodium free | false |  |\n| unsalted | false |  |\n| very low sodium | false |  |\n\n## ALLERGEN_TABLE\n| allergen contain statement | allergen contain break-down list | allergen does-not-contain statement | allergen does-not-contain statement break-down list | allergen contain on equipment statement | allergen contain on equipment break-down list| \n| ------- | -------- | -------- | ------- | -------- | -------- |\n| Contains: Soybeans, Sulfites, Fish and Tree Nuts (Coconut) | Soybeans, Sulfites, Fish, Tree Nuts |  |  |  |  |\n\n## HEADER_TABLE\n| product name | brand name | primary size | secondary size | third size | full size text description | count |\n| ------- | -------- | -------- | ------- | -------- | -------- | -------- |\n| Yaki Be-fun | Kenmin Foods | 2.29 oz | 65g |  | NET WT. 2.29 OZ ( 65g ) |  |\n\n## INGREDIENT_TABLE\n| is product supplement ? (answer boolean) | ingredient statement | \n| ------- | -------- |\n| false | RICE, STARCH ( TAPIOCA , POTATO , CORN ) , SOY SAUCE ( WATER , SOYBEANS , WHEAT , SALT ) , SALT , KELP EXTRACT , MONOSODIUM GLUTAMATE , FISH EXTRACT ( MALTODEXTRIN , BONITO EXTRACT , SALT , FISH EXTRACT POWDER ( EASTERN LITTLE TUNA , FRIGATE MACKEREL , SKIPJACK TUNA ) , YEAST EXTRACT ) , SUGAR , GINGER PASTE , MONO - AND DIGLYCERIDES OF FATTY ACIDS , SODIUM METAPHOSPHATE , SODIUM TRIPOLYPHOSPHATE , TETRASODIUM PYROPHOSPHATE , CARBOXYMETHYL CELLULOSE , GARLIC POWDER , ONION POWDER , DISODIUM 5 \' - RIBONUCLEOTIDE , CARAMEL COLOR , YEAST EXTRACT , PEPPER , SUCROSE FATTY ACID ESTERS , COLOR ( RIBOFLAVIN ) , ROSEMARY EXTRACT . |\n\n## PHYSICAL_TABLE\n| upc-12 or gtin-12 |\n| ------- |\n| 50009312013 |\n\n## MARKETING_TABLE\n| have QR code (answer is boolean) | have Instagram icon ? | have Pinterest icon ? | have Youtube icon ? | have Facebook icon ? | have twitter icon ? | social media list | website list | social media text list | enlarged to show (answer is boolean) |\n| ------- | -------- | -------- | -------- | ------- | -------- | -------- | -------- | -------- | -------- |\n| false | false | false | false | false | false |  | http://www.kenmin.co.jp |  | false |\n\n## INSTRUCTION_TABLE\n| storage instructions (answer are multiple string) | cooking instructions  (answer are multiple string) | usage instructions (answer are multiple string) | usage time instruction (answer are multiple string)| other instructions (answer are multiple string)|\n| ------- | -------- | -------- | ------- | -------- |\n|  | Heat frying pan and add one and half table spoon of cooking oil. Lay down pork belly strips and layer with Yaki - Befun noodles , and ( vegetables in this particular order .<br>Add 6.7 ounces of water , seal with a lid and heat on high heat for 3 mins .<br>After 3 minutes , remove the lid and lightly mix the ingredients around and let the remaining water evaporate . Serve hot . |  |  | * 2 servings add 11.5 ounces of water .<br>* sesame oil can be added for extra flavor |\n\n## SUPPLY_CHAIN_TABLE\n| country of origin | manufacture name | manufacture date | manufacture phone number | manufacture street address | manufacture city | manufacture state | manufacture zipCode |\n| ------- | -------- | -------- | ------- | ------- | -------- | -------- | ------- |\n| Thailand | KENMIN FOODS CO., LTD. |  |  |  |  |  |  |\n\n## DEBUG_TABLE\n| question (question from DEBUG LIST below) | gemini answer |\n| ------- | -------- |\n| i see you think too deeply for example when you see "free from artificial flavor" and you think product claim "does not contain added flavor". That is not what i want it must say that product claim "does not contain artificial flavor". I do not how to prompt and make you understand that so next time you will no make same mistake help me write prompt sentences to fix that | I understand. You are looking for explicit claims made on the product packaging and not inferences based on the ingredients or lack thereof. I will focus on extracting direct product claims from the text and avoid making assumptions.  For example, instead of assuming "no added flavors" from "free from artificial flavors," I will only report if the product explicitly states "no added flavors." |\n| product does not say about antibiotics but you still include in extra claim list ? why ? | You are right. I\'ve removed "antibiotics" from the extra claim list. It appears I was pulling from a larger list of common claims and not focusing specifically on what the product packaging stated. I will make sure to only include claims that are explicitly mentioned on the product packaging in the future. |\n',
  },
};
