export const make_markdown_all_prompt = ({
  ocrText,
  imageCount,
}: {
  ocrText?: string;
  imageCount?: number;
}) => {
  return `OCR texts from ${imageCount} provided images:
${ocrText}

VALIDATION AND FIX BUGS:
1) To avoid any deduction and ensure accuracy, if the product explicitly states that it "does not contain [specific ingredient]" or "is free from [specific ingredient]". Do not infer or deduce information from similar phrases. For example, if the product says "free from artificial flavors," do not assume it also means "does not contain added flavors." Only report what the text directly states.
2) Only be using the information explicitly provided in the product images and not drawing conclusions based on the ingredient list. I will focus on directly extracting product claims from the text on the packaging and avoid making deductions based on the presence or absence of specific ingredients.
Ex 1: if product have something in ingredient list. That cannot conclude that product claim to have this thing. Claim must be a statement or texts on the packaging make claim on a thing.
3) "NON GMO Project VERIFIED" does not claim "not fried". It is about non-GMO food and products.
4) Product info could contain multiple languages info. Only return provided info in english.
5) Only return all markdown tables that i require you to return.
6) There are some tables that i require return row items with specific given condition. Please check it carefully.
7) you keep return only 10 or 11 digits for upc-12. It is wrong. 

IMPORTANT RULES:
1) "allergen" rules:
+ below is the standardized allergen list: 
"corn"
"crustacean shellfish"
"dairy"
"egg"
"fish"
"milk"
"oats"
"peanuts / peanut oil"
"phenylalanine", "seeds"
"sesame"
"soy / soybeans"
"tree nuts"
"wheat".

+ "allergen does-not-contain statement" is the exact context that you found on provided images about allergen info, that product claim not to contain.
Ex 1: "non-dairy" text mean does not contain allergen ingredient of "dairy"

+ "allergen contain statement" is the exact context that you found on provided images about allergen info, ususally start with "contains", "contains:", "may contains:", ....

+ "allergen contain on equipment statement" is the exact context that you found on provided images about list of allergen ingredients that is said they may be contained in/on manufacturing equipments.
ex 1: "manufactured on equipment that also processes product containing ..."

2) "extra claim list" rules:
+ "added color" claim does not mean product claim "artificial color".
+ "added color" claim does not mean product claim "artificial color".
+ "vegan" text only does not mean "vegan ingredients".
+ "natural" text only does not mean "natural ingredients".
+ "gluten free" does not mean product not contain "allergen". 
+ "allergen" claim detected from text such as "allergen free", "do not contain allergen", "product contain allergen", ...
+ "real ingredient" not mean "natural flavor" or "naturally flavored".

3) "sugar claim list" rules:
+ "contain unsweetened" claim does not mean "no contain sugar added"
+ "low sweet" not mean "no contain sugar added"

4) "header" table rules:
+ header table only have 1 row item so you must carefully examine the images.
+ "primary size" and "secondary size" and "third size" is a quantity measurement of product in two different unit of measurement. They are not info from "serving size" in nutrition fact.
+ "count" is the count number of smaller unit inside a package, or a display shipper, or a case, or a box.
+ "full size text description" is the whole quantity measurement description statement of the product on image. It is usually appear on the front face of product.

5) "ingredient" table rules:
+ is the list of statements about ingredients of product (since product can have many ingredients list)
+ "ingredient statement" is content start right after a prefix text such as "ingredients:" or "Ingredients:" or "INGREDIENTS:" or "other ingredients:".

6) "marketing" table rules:
+ "social media list" is the list of social media method mentioned on product images (such as "facebook", "google", "instagram", "pinterest", "snapchat", "tiktok", "youtube", "twitter", ...).
+ "website list" is all website link found on product (website link exclude "nongmoproject.org") and be careful the content after slash could be phone number.
+ "social media text" is a list of text usually start with "@", or "#" those can be used to search the product on social media. Hint, it is usually next to social media icons.
+ "enlarge to show" is true if statement such as "enlarged to show..." seen on product image.

7) "physical" rules:
+ "upc-12 or gtin-12" is a code contain 12 digit numbers, it usually appear on product image with structure that have 10 digit numbers at between two other digit numbers.
Ex: "0   4562342221   5" as you can see there are two digit numbers at the start is 0 and at the end is 5. And the "upc-12 or gtin-12" here = 045623422215

8) "instruction" table rules:
+ "other instruction" such as
ex 1: "best if consumed ..."
ex 2: "use it with lemon..."
+ "storage instruction" such as "keep refrigerated"
+ "usage time instruction" such "use by a time", "use within a time", "use before a time"
Ex 1: "use within 30 days ..."


RESULT THAT I NEED:
Carefully examine provided images above. They are captured images of one product, and return info from provided images that match all listed requirements and rules above with all markdown tables format below

+ extra claim list info recorded in markdown table format below 
(ROW RETURN CONDITION: only return row item if "explicitly and directly mentioned in product info without implied from other text" value = true )

EXTRA_CLAIM_TABLE
| extra item |  explicitly and directly mentioned in product info without implied from other text (answer is true/false/unknown) | Does the product explicitly state contain it ? (answer is yes/no) |  Does the product explicitly state to not contain it ? (answer is yes/no)  |  do you know it through which info ? (answer are  "ingredient list"/ "marketing text on product"/ "nutrition fact"/ "others") (answer could be multiple string since the info can appeared in multiple sources) | how do you know that ? and give me you explain (answer in string) |
| ------- | -------- | ------- | ------- |
| 1,4-dioxane | ...
| active yeast | ...
| added antibiotics | ...
| added colors | ...
| added dyes | ...
| added flavors | ...
| added fragrances | ...
| added hormones | ...
| added nitrates | ...
| added nitrites | ...
| added preservatives | ...
| additives | ...
| alcohol | ...
| allergen | ...
| aluminum | ...
| amino acids | ...
| ammonia | ...
| animal by-products | ...
| animal derivatives | ...
| animal ingredients | ...
| animal products | ...
| animal rennet | ...
| antibiotics | ...
| artificial additives | ...
| artificial colors | ...
| artificial dyes | ...
| artificial flavors | ...
| artificial fragrance | ...
| artificial ingredients | ...
| artificial preservatives | ...
| binders and/or fillers | ...
| bleach | ...
| bpa (bisphenol-a) | ...
| butylene glycol | ...
| by-products | ...
| caffeine | ...
| carrageenan | ...
| casein | ...
| cbd / cannabidiol | ...
| chemical additives | ...
| chemical colors | ...
| chemical dyes | ...
| chemical flavors | ...
| chemical fragrances | ...
| chemical ingredients | ...
| chemical preservatives | ...
| chemical sunscreens | ...
| chemicals | ...
| chlorine | ...
| cholesterol | ...
| coatings | ...
| corn fillers | ...
| cottonseed oil | ...
| dyes | ...
| edta | ...
| emulsifiers | ...
| erythorbates | ...
| expeller-pressed oils | ...
| fillers | ...
| fluoride | ...
| formaldehyde | ...
| fragrances | ...
| grain | ...
| hexane | ...
| hormones | ...
| hydrogenated oils | ...
| kitniyos / kitniyot (legumes) | ...
| lactose | ...
| latex | ...
| msg | ...
| natural additives | ...
| natural colors | ...
| natural dyes | ...
| natural flavors or naturally flavored | ...
| natural ingredients | ...
| natural preservatives | ...
| nitrates/nitrites | ...
| omega fatty acids | ...
| paba | ...
| palm oil | ...
| parabens | ...
| pesticides | ...
| petro chemical | ...
| petrolatum | ...
| petroleum byproducts | ...
| phosphates | ...
| phosphorus | ...
| phthalates | ...
| pits | ...
| preservatives | ...
| probiotics | ...
| rbgh/bst | ...
| rennet | ...
| salicylates | ...
| sea salt | ...
| shells/ shell pieces | ...
| silicone | ...
| sles (sodium laureth sulfate) | ...
| sls (sodium lauryl sulfate) | ...
| stabilizers | ...
| starch | ...
| sulfates | ...
| sulfides | ...
| sulfites / sulphites | ...
| sulfur dioxide | ...
| synthetic additives | ...
| synthetic colors | ...
| synthetic dyes | ...
| synthetic flavors | ...
| synthetic fragrance | ...
| synthetic ingredients | ...
| synthetic preservatives | ...
| synthetics | ...
| thc / tetrahydrocannabinol | ...
| toxic pesticides | ...
| triclosan | ...
| vegan ingredients | ...
| vegetarian ingredients | ...
| yeast | ...
| yolks | ...

2) Sugar claim info recorded in markdown table format below 
(ROW RETURN CONDITION: only return row item if "does product claim that sugar claim" value = true )

SUGAR_CLAIM_TABLE
| sugar claim | does product claim that sugar claim? (answer are true/false/unknown) (unknown when not mentioned) | do you know it through which info ? (answer are "ingredient list"/ "nutrition fact"/ "marketing text on product"/ "others") (answer could be multiple string from many sources) (answer could be multiple string from many sources)| how do you know that ? and give me you explain (answer in string) |
| ------- | -------- | -------- |
| contain acesulfame k | ...
| contain agave | ...
| contain allulose | ...
| contain artificial sweetener | ...
| contain aspartame | ...
| contain beet sugar | ...
| contain cane sugar | ...
| contain coconut/coconut palm sugar | ...
| contain fruit juice | ...
| contain high fructose corn syrup | ...
| contain honey | ...
| contain low sugar | ...
| contain lower sugar | ...
| contain monk fruit | ...
| contain natural sweeteners | ...
| no contain acesulfame k | ...
| no contain added sugar | ...
| no contain agave | ...
| no contain allulallallose | ...
| no contain artificial sweetener | ...
| no contain aspartame | ...
| no contain cane sugar | ...
| no contain coconut/coconut palm sugar | ...
| no contain corn syrup | ...
| no contain high fructose corn syrup | ...
| no contain refined sugars | ...
| no contain saccharin | ...
| no contain splenda/sucralose | ...
| no contain stevia | ...
| no contain sugar | ...
| no contain sugar added | ...
| no contain sugar alcohol | ...
| no contain tagatose | ...
| no contain xylitol | ...
| contain reduced sugar | ...
| contain refined sugar | ...
| contain saccharin | ...
| contain splenda/sucralose | ...
| contain stevia | ...
| contain sugar alcohol | ...
| contain sugar free | ...
| contain sugars added | ...
| contain tagatose | ...
| contain unsweetened | ...
| contain xylitol | ...

+ Fat claim info of product images recorded in markdown table format below 
(ROW RETURN CONDITION: only return row item if "does product claim that fat claim" value = true )

FAT_CLAIM_TABLE
| fat claim | does product claim that fat claim? (answer are true/false/unknown) (unknown when not mentioned) | do you know it through which info ? (answer are "ingredient list"/ "nutrition fact"/ "marketing text on product"/ "others") (answer could be multiple string from many sources) | how do you know that ? and give me you explain (answer in string) |
| ------- | -------- | -------- |
| fat free | ...
| free of saturated fat | ...
| low fat | ...
| low in saturated fat | ...
| no fat | ...
| no trans fat | ...
| reduced fat | ...
| trans fat free | ...
| zero grams trans fat per serving | ...
| zero trans fat | ...

+ other claim list info recorded in markdown table format below 
(ROW RETURN CONDITION: only return row item if "does product explicitly claim this claim" value = true )

OTHER_CLAIM_TABLE
| other claim | does product explicitly claim this claim? (answer are true/false/unknown) (unknown when not mentioned) | do you know it through which info ? (answer are "ingredient list"/ "nutrition fact"/ "marketing text on product"/ "others") (answer could be multiple string from many sources) | how do you know that ? and give me you explain (answer in string) |
| ------- | -------- | -------- |
| 100% natural | ...
| 100% natural ingredients | ...
| 100% pure | ...
| acid free | ...
| aeroponic grown | ...
| all natural | ...
| all natural ingredients | ...
| aquaponic/aquaculture grown | ...
| baked | ...
| biodegradable | ...
| cage free | ...
| cold-pressed | ...
| direct trade | ...
| dolphin safe | ...
| dry roasted | ...
| eco-friendly | ...
| farm raised | ...
| filtered | ...
| free range | ...
| freeze-dried | ...
| from concentrate | ...
| grade a | ...
| greenhouse grown | ...
| heat treated | ...
| heirloom | ...
| homeopathic | ...
| homogenized | ...
| hydroponic grown | ...
| hypo-allergenic | ...
| irradiated | ...
| live food | ...
| low acid | ...
| low carbohydrate | ...
| low cholesterol | ...
| macrobiotic | ...
| minimally processed | ...
| natural | ...
| natural botanicals | ...
| natural fragrances | ...
| natural ingredients | ...
| no animal testing | ...
| no sulfites added | ...
| non gebrokts | ...
| non-alcoholic | ...
| non-irradiated | ...
| non-toxic | ...
| not fried | ...
| not from concentrate | ...
| pasteurized | ...
| pasture raised | ...
| prairie raised | ...
| raw | ...
| responsibly sourced palm oil | ...
| sprouted | ...
| un-filtered | ...
| un-pasteurized | ...
| unscented | ...
| vegetarian or vegan diet/feed | ...
| wild | ...
| wild caught | ...

+ calorie claim info recorded in markdown table format below:
(ROW RETURN CONDITION: only return row item if "does product explicitly claim this claim" value = true )

CALORIE_CLAIM_TABLE
| calorie claim | does product explicitly claim this claim? (answer are true/false/unknown) (unknown when not mentioned) | do you know it through which info ? (answer are "ingredient list"/ "nutrition fact"/ "marketing text on product"/ "others") (answer could be multiple string from many sources) |
| ------- | -------- |
| low calorie | ...
| reduced calorie | ...
| zero calorie | ...

+ salt claim info recorded in markdown table format below:
(ROW RETURN CONDITION: only return row item if "does product explicitly claim this claim" value = true )

SALT_CLAIM_TABLE
| salt claim | does product explicitly claim this claim? (answer are true/false/unknown) (unknown when not mentioned) | do you know it through which info ? (answer are "ingredient list"/ "nutrition fact"/ "marketing text on product"/ "others") (answer could be multiple string from many sources) |
| lightly salted | ...
| low sodium | ...
| no salt | ...
| no salt added | ...
| reduced sodium | ...
| salt free | ...
| sodium free | ...
| unsalted | ...
| very low sodium | ...

+ Allergen info recorded in markdown table format below:
 
ALLERGEN_TABLE
| allergen contain statement | allergen contain break-down list | allergen does-not-contain statement | allergen does-not-contain statement break-down list | allergen contain on equipment statement | allergen contain on equipment break-down list| 
| ------- | -------- | -------- | ------- | -------- | -------- |

+ Header info with table format below:
(IMPORTANT NOTE: remember header table only have one row item)

HEADER_TABLE
| product name | brand name | primary size | secondary size | third size | full size text description | count |
| ------- | -------- | -------- | ------- | -------- | -------- | -------- |

+ Ingredient info with table format below:

INGREDIENT_TABLE
| is product supplement ? (answer boolean) | ingredient statement | 
| ------- | -------- |

+ Physical info with table format below

PHYSICAL_TABLE
| upc-12 or gtin-12 |
| ------- |

+ Marketing info with table format below:

MARKETING_TABLE
| have QR code (answer is boolean) | have Instagram icon ? | have Pinterest icon ? | have Youtube icon ? | have Facebook icon ? | social media list | website list | social media text list | enlarged to show (answer is boolean) |
| ------- | -------- | -------- | ------- | ------- |

+ Instruction info with table format below:

INSTRUCTION_TABLE
| storage instructions (answer are multiple string) | cooking instructions  (answer are multiple string) | usage instructions (answer are multiple string) | usage time instruction (answer are multiple string)| other instructions (answer are multiple string)|
| ------- | -------- | -------- | ------- |

+ supply chain info with table format below:

SUPPLY_CHAIN_TABLE
| country of origin | manufacture name | manufacture date | manufacture phone number | manufacture street address | manufacture city | manufacture state | manufacture zipCode |
| ------- | -------- | -------- | ------- | ------- | -------- | -------- | ------- |



+ Debug table is gemini answer recorded in markdown table format below:

DEBUG_TABLE
| question (question from DEBUG LIST below) | gemini answer |
| ------- | -------- |

DEBUG LIST:
1) i see you think too deeply for example when you see "free from artificial flavor" and you think product claim "does not contain added flavor". That is not what i want it must say that product claim "does not contain artificial flavor". I do not how to prompt and make you understand that so next time you will no make same mistake help me write prompt sentences to fix that
`;
};

// 2) the problem is that some claim you concluded from ingredient list? but the product claim is not retrieved from ingredient list
// 3) i only require the result of table with nutrient row that match my conditions but i see you actually created row with initial data not provided by me ? i do not want that can you help me with write prompt to fix that?
