const test = `
important requirements:

carefully examine provided images above. They are captured images of one product, and return info from provided images that match all listed requirements and rules above with markdown tables format below

1) claim info of product images recorded in markdown table
+ TABLE_NAME = "SUGAR CLAIM"
+ Table format:
TABLE_NAME
| sugar claim | does product claim that sugar claim? (answer are true/false/unknown) (unknown when not mentioned)  | how do you know? (answer in string) | negative  statement or positive statement fount on product images (negative statement such as "does not contain", "free of", "do not use",... and positive statement such as "have ...", "contain", "use...", "made with...") (answer are negative/positive) |
| ------- | --------  | --------  |
| no sugar | ...
| no contain ACESULFAME K | ...
| lower sugar | ...
| contain ACESULFAME K | ...
| contain artificial sweetener | ...
| sugar free | ...
| no contain artificial sweetener | ...
| no sugar added | ...
| no contain SPLENDA/SUCRALOSE | ...
| contain stevia | ...
| contain sugars added | ...
| contain splenda/sucralose | ... 

2) Debug table is gemini answer recorded in table
+ TABLE_NAME = "DEBUG_TABLE"
+ Table format:
TABLE_NAME
| question (question from debug list below) | gemini answer |
| ------- | -------- |

debug list:
` as any;
