// | extra item | is mentioned on product ?  | mentioned on which text on product ? | do you know it through which source of info ? (answer are  "ingredient list"/ "marketing text on product"/ "nutrition fact"/ "others") (multiple string) | product contain it ? (answer is yes/no) |
// MARKETING_TEXT_TABLE

// 10) "marketing text table" rules:
// + is the list of all texts or paragraphs to marketing for products that appeal customer to buy

// IMPORTANT DEFINITIONS:
// + "added color" is not "artificial color".
// + "vegan" is not mean "vegan ingredients".
// + "natural" is not mean "natural ingredients".
// + "gluten free" is not mean "allergen".
// + "Gluten Free" is not mean "colors".
// + "real ingredient" not mean "natural flavor" or "naturally flavored".
// + "pesticide" is not mean "antibiotics".
// + "Organic" not mean "no animal ingredients"
// + "vegan certifier" not mean "vegan ingredient"
// + "international ingredients" not mean "chemical ingredient"
// + "allergen" claim detected from text such as "allergen free", "do not contain allergen", "product contain allergen", ...

// CONDITION FOR ROW TO SHOW IN TABLE BELOW:
// + only return row items that its "sugar item explicitly and directly state in a text on product  without implying from other text" value = "yes" and remove all unqualified rows from table)

// CONDITION FOR ROWS TO SHOW FOR TABLE BELOW:
// + only return row items if its answer of "item explicitly and directly state in a text on product  without implying from other text" = "yes" and remove all unqualified rows from table below

// + "ingredient break-down" is the break-down list of ingredients statement. Remember that sub-ingredients in the parenthesis or bracket of main ingredient item is recorded as one ingredient item info.
// Ex1: "STARCH (TAPIOCA, POTATO, CORN)" is an ingredient item in the list

// 11) "marketing text table" rules:
//  + is the list of all texts or paragraphs to marketing for products that appeal customer to buy

// + "all other instructions" are all other instructions see examples
// Ex 1: SEE NUTRITION INFORMATION FOR FAT AND SATURATED FAT ...

// + allergen table only must have one row data so the list must be recorded in one cell and split by ", "

// + "break-down list about allergen things product does not contain"
// example 1: "milk and peanut free" should be recorded as "milk/peanut"

// PHYSICAL_TABLE

// 12) Physical info with table format below

// PHYSICAL_TABLE
// | upc code on the barcode  | The lot number is located on the left side of the UPC code (only one digit number inside the barcode) | all numbers on the right side of lot number |
// | ------- | ------- | ------- |

// + "text on images that tell allergens product does not contain" are the exact contexts that you found on provided images about allergen info, that product claim to not contain or free of or free.
// example 1: "contain no wheat, milk"
// example 2: "does not contain wheat, milk"
// example 3: "free of wheat, milk"
// example 4: "non-dairy" text mean does not contain allergen ingredient of "dairy"
// example 5: "no egg"

// + "allergen contain statements" are the exact contexts that you found on provided images about allergen info, usually start with "contains:", "contain", "may contain", "may contain:", "allergen statement:, ... NOT due to sharing manufacturing equipments or in same facility with other products.
// Example 1: "allergen statement: contains milk"
// Example 2: "may contain: milk, peanut"

// + "allergen contain break-down list" is the allergen ingredients from "allergen contain statement" and do not collect from product ingredient list.

// + "statement about allergen contain on manufacturing equipments or in facility or due to shared equipments" are the exact contexts that you found on provided images about list of allergen ingredients that is said they could present on the product since manufacturing equipments are also used to make other products or in the same facility .
// ex 1: "manufactured on equipment that also processes product containing ..."
// ex 2: "made in a facility that also processes ... "
// ex 3: "tree nuts, wheat present in facility"

// + "break-down list of allergens for statement about allergen contain on manufacturing equipments or in facility or due to shared equipments" is the break-down list of all ingredients that is stated to present in facility or manufacturing equipments. Do not include ingredients that say is not present on facility or manufacturing equipment.
// Example 1: "Manufactured in a egg and milk free facility that also processes peanut, wheat products" should be recorded as "peanut/wheat" since text "in a egg and milk free facility" mean the egg and milk is not present in facility.

// + "allergen break-down list from that statement" is a string list
// ex 1: "oats/milk"

///* LABELING
// IMPORTANT NOTE:
// + LABELING_INFO_TABLE only have one row data, the multiple values must split by "/"
// + labeling info could be easily detected by some icons with text on provided images.
// + remember when product state "something free" it mean product free of that thing (such as soy free, dairy free, ...)
// Example 1: "gluten free" mean product not contain "gluten"
// Example 2: "nuts free" mean product not contain "nuts"

// TABLE FORMAT:
// LABELING_INFO_TABLE
// | things that labels/logos indicate product free of (multiple things name split by "/") | things that labels/logos indicate product contain (multiple things name split by "/")|
// | ------- | -------- |
// END__LABELING__INFO__TABLE

// conclude from label item what product say it does not contain (split by "/") | conclude from label item what product say it contain ? (split by "/") |

// Q_AND_A_TABLE;

// 1) Q_AND_A TABLE recorded in markdown TABLE FORMAT below

// TABLE FORMAT:
// Q_AND_A_TABLE
// | question | short answer |
// | ------- | -------- |
// | do product state soy free ? |
// END__Q__AND__A__TABLE

// + "cooking instructions" are all statements, paragraphs, or phrases about cooking with product (such as recipes, or all steps to cook product with kitchen devices, ...)

// + "usage instructions" are all instruction sentences about how to use product excluding all "cooking instructions"
// Example 1: "suggested use: 2 cups at one time."
// Example 1: "enjoy within 20 days for best taste"

// + "storage instruction" are all instruction sentences about how to storage product.
// Example 1: "reseal for freshness"
// Example 2: "keep refrigerated"

// 1) To avoid any deduction and ensure accuracy.
//   OCR texts from ${imageCount} provided images:
// ${ocrText}

export const make_markdown_attr_2_prompt = ({
  ocrText,
  imageCount,
}: {
  ocrText?: string;
  imageCount?: number;
}) => {
  return `
All provided photos are the captured from different angle of one product. There might be some parts of info on photos might be duplicated when photos was taken from many different angles.

From provided photos give me all exact texts and exacts paragraphs you see from provided photos.
`;
};

// PROCESS_CLAIM_TABLE
// CALORIE_CLAIM_TABLE
// SALT_CLAIM_TABLE
// FIRST_EXTRA_CLAIM_TABLE
// SECOND_EXTRA_CLAIM_TABLE
// THIRD_EXTRA_CLAIM_TABLE

// 3) PROCESS_CLAIM_TABLE info recorded in markdown table format below:

// IMPORTANT NOTE:in
// + "live food" is living animals used as food for pet.

// TABLE FORMAT:
// PROCESS_CLAIM_TABLE
// | processing text | do the processing text present on provided images? (answer is yes/no/unknown) (answer is yes/no/unknown)? | do you know it through which info ? (answer are "ingredient list"/ "nutrition fact panel"/ "marketing text on product"/ "others") (answer could be multiple string from many sources) | return exact sentence or phrase on provided image that prove it |
// | ------- | -------- | -------- | -------- |
// | 100% natural | ...
// | 100% natural ingredients | ...
// | 100% pure | ...
// | acid free | ...
// | aeroponic grown | ...
// | all natural | ...
// | all natural ingredients | ...
// | aquaponic/aquaculture grown | ...
// | aquaponic grown | ...
// | aquaculture grown | ...
// | baked | ...
// | bake | ...
// | biodegradable | ...
// | cage free | ...
// | cold-pressed | ...
// | direct trade | ...
// | dolphin safe | ...
// | dry roasted | ...
// | eco-friendly | ...
// | farm raised | ...
// | filtered | ...
// | free range | ...
// | freeze-dried | ...
// | from concentrate | ...
// | grade a | ...
// | greenhouse grown | ...
// | heat treated | ...
// | heirloom | ...
// | homeopathic | ...
// | homogenized | ...
// | hydroponic grown | ...
// | hypo-allergenic | ...
// | irradiated | ...
// | live food | ...
// | low acid | ...
// | low carbohydrate or low-carb | ...
// | low cholesterol | ...
// | macrobiotic | ...
// | minimally processed | ...
// | natural | ...
// | natural botanicals | ...
// | natural fragrances | ...
// | natural ingredients | ...
// | no animal testing | ...
// | no sulfites added | ...
// | non gebrokts | ...
// | non-alcoholic | ...
// | non-irradiated | ...
// | non-toxic | ...
// | non-fried | ...
// | not from concentrate | ...
// | pasteurized | ...
// | pasture raised | ...
// | prairie raised | ...
// | raw | ...
// | responsibly sourced palm oil | ...
// | sprouted | ...
// | un-filtered | ...
// | un-pasteurized | ...
// | unscented | ...
// | vegetarian or vegan diet/feed | ...
// | vegetarian | ...
// | vegan diet | ...
// | vegan feed | ...
// | wild | ...
// | wild caught | ...
// END_PROCESS_CLAIM_TABLE

// 4) CALORIE CLAIM TABLE info recorded in markdown table format below:

// TABLE FORMAT:
// CALORIE_CLAIM_TABLE
// | calorie claim | does product explicitly claim the calorie claim? (answer are yes/no/unknown) (unknown when not mentioned) | do you know it through which info ? (answer are "ingredient list"/ "nutrition fact panel"/ "marketing text on product"/ "others") (answer could be multiple string from many sources) |
// | ------- | -------- | -------- |
// | have low calorie | ...
// | have reduced calorie | ...
// | have zero calorie | ...
// END_CALORIE_CLAIM_TABLE

// 5) SALT CLAIM TABLE info recorded in markdown table format below:

// TABLE FORMAT:
// SALT_CLAIM_TABLE
// | salt claim | does product explicitly claim this claim? (answer are yes/no/unknown) (unknown when not mentioned) | do you know it through which info ? (answer are "ingredient list"/ "nutrition fact panel"/ "marketing text on product"/ "others") (answer could be multiple string from many sources) |
// | ------- | -------- | -------- |
// | lightly salted | ...
// | low sodium | ...
// | no salt | ...
// | no salt added | ...
// | reduced sodium | ...
// | salt free | ...
// | sodium free | ...
// | unsalted | ...
// | very low sodium | ...
// END_SALT_CLAIM_TABLE

// 6) FIRST EXTRA CLAIM TABLE info recorded in markdown table format below:

// IMPORTANT NOTE:
// + text like "contain ..." or "contain no ..." is "marketing text on product" and NOT "ingredient list"

// + "do you know it through those sources info ?" could be multiple sources splitted by "/". Please prioritize read data from the source of "marketing text on product" over other sources.

// TABLE FORMAT:
// FIRST_EXTRA_CLAIM_TABLE
// | extra item | is text about item present on provided images ? (answer is yes/no/unknown) | How product state about it ? (answer are "free from" / "made without" / "no contain" / "contain" / "free of" / "no" / "free" / "flavor with" / "other" / "do not use" / "may contain" )  |  do you know it through those sources info ? (answer are  "ingredient list"/ "marketing text on product"/ "nutrition fact panel"/ "NA") | how do you know that? |
// | ------- | -------- | ------- | ------- | ------- |
// | additives | ...
// | artificial additives | ...
// | chemical additives | ...
// | synthetic additives | ...
// | natural additives | ...
// | added colors | ...
// | artificial colors | ...
// | chemical colors | ...
// | synthetic colors | ...
// | natural colors | ...
// | dyes | ...
// | added dyes | ...
// | artificial dyes | ...
// | chemical dyes | ...
// | synthetic dyes | ...
// | natural dyes | ...
// | added flavors | ...
// | artificial flavors | ...
// | chemical flavors | ...
// | synthetic flavors | ...
// | natural flavors | ...
// | naturally flavored | ...
// | added fragrances | ...
// | artificial fragrance | ...
// | chemical fragrances | ...
// | synthetic fragrance | ...
// | preservatives | ...
// | added preservatives | ...
// | artificial preservatives | ...
// | chemical preservatives | ...
// | synthetic preservatives | ...
// | natural preservatives | ...
// | artificial ingredients | ...
// | chemical ingredients | ...
// | synthetic ingredients | ...
// | natural ingredients | ...
// | animal ingredients | ...
// | chemical sunscreens | ...
// | animal by-products | ...
// | animal derivatives | ...
// | animal products | ...
// | animal rennet | ...
// | antibiotics | ...
// | added antibiotics | ...
// | synthetics | ...
// | chemicals | ...
// | hormones | ...
// | added hormones | ...
// | nitrates | ...
// | nitrites | ...
// | added nitrates | ...
// | added nitrites | ...
// | yeast | ...
// | active yeast | ...
// END_FIRST_EXTRA_CLAIM_TABLE

// 7) SECOND_EXTRA_CLAIM_TABLE info recorded in markdown table format below:

// IMPORTANT NOTE:
// + no note

// TABLE FORMAT:
// SECOND_EXTRA_CLAIM_TABLE
// | extra item | is text about item present on provided images? (answer is yes/no/unknown) | How product state about it ? (answer are "free from" / "made without" / "no contain" / "contain" / "free of" / "no" / "free" / "flavor with" / "other" / "do not use" / "may contain") |  do you know it through which info ? (answer are  "ingredient list"/ "marketing text on product"/ "nutrition fact panel"/ "NA") (answer could be multiple string since the info can appeared in multiple sources) | how do you know that ? |
// | ------- | -------- | ------- | ------- | ------- |
// | omega fatty acids | ...
// | pesticides | ...
// | 1,4-dioxane | ...
// | alcohol | ...
// | allergen | ...
// | gluten | ...
// | aluminum | ...
// | amino acids | ...
// | ammonia | ...
// | cholesterol | ...
// | coatings | ...
// | corn fillers | ...
// | cottonseed oil | ...
// | edta | ...
// | emulsifiers | ...
// | erythorbates | ...
// | expeller-pressed oils | ...
// | fillers | ...
// | fluoride | ...
// | formaldehyde | ...
// | fragrances | ...
// | grain | ...
// | hexane | ...
// | hydrogenated oils | ...
// | kitniyos | ...
// | kitniyot | ...
// | lactose | ...
// | latex | ...
// | msg | ...
// | paba | ...
// | palm oil | ...
// | parabens | ...
// END_SECOND_EXTRA_CLAIM_TABLE

// 8) THIRD_EXTRA_CLAIM_TABLE info recorded in markdown table format below:

// IMPORTANT NOTE:
// + "vegan" not mean "vegan ingredients"

// TABLE FORMAT:
// THIRD_EXTRA_CLAIM_TABLE
// | extra item | is text about item present on provided images? (answer is yes/no/unknown) |  How product state about it ? (answer are "free from" / "made without" / "no contain" / "contain" / "free of" / "no" / "free" / "flavor with" / "other" / "do not use" / "may contain") |  do you know it through which info ? (answer are  "ingredient list"/ "marketing text on product"/ "nutrition fact panel"/ "NA") (answer could be multiple string since the info can appeared in multiple sources) | how to you know that ? |
// | ------- | -------- | ------- | ------- | ------- |
// | petro chemical | ...
// | petrolatum | ...
// | petroleum byproducts | ...
// | phosphates | ...
// | phosphorus | ...
// | phthalates | ...
// | pits | ...
// | probiotics | ...
// | rbgh | ...
// | rbst | ...
// | rennet | ...
// | salicylates | ...
// | sea salt | ...
// | shells pieces | ...
// | shell pieces | ...
// | silicone | ...
// | sles (sodium laureth sulfate) | ...
// | sls (sodium lauryl sulfate) | ...
// | stabilizers | ...
// | starch | ...
// | sulfates | ...
// | sulfides | ...
// | sulfites | ...
// | sulphites | ...
// | sulfur dioxide | ...
// | thc | ...
// | tetrahydrocannabinol | ...
// | toxic pesticides | ...
// | triclosan | ...
// | vegan ingredients | ...
// | vegetarian ingredients | ...
// | yolks | ...
// | binders and/or fillers | ...
// | bleach | ...
// | bpa (bisphenol-a) | ...
// | butylene glycol | ...
// | by-products | ...
// | caffeine | ...
// | carrageenan | ...
// | casein | ...
// | cbd / cannabidiol | ...
// | chlorine | ...
// END_THIRD_EXTRA_CLAIM_TABLE
