version: '3.7'

services:
  label_studio:
    image: heartexlabs/label-studio:latest
    ports:
      - '8080:8080'
    environment:
      - LABEL_STUDIO_LOCAL_FILES_SERVING_ENABLED=true
      - LABEL_STUDIO_LOCAL_FILES_DOCUMENT_ROOT=/label-studio/data/yolo
    volumes:
      - ./mydata:/label-studio/data
