name: food-ocr CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: vps-hostinger

    strategy:
      matrix:
        node-version: [18.17]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    env:
      GOOGLE_CREDENTIAL_2: ${{ secrests.GOOGLE_CREDENTIALs}
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
