name: Node.js CI

on:
  push:
    branches: ['main']

jobs:
  prepare:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [17.18.0]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.5

      - name: Install dependencies
        run: npm ci
  env:
    runs-on: self-hosted

    steps:
      - name: Create env file
        run: |
          echo "GOOGLE_CREDENTIALS=${{ secrets.GOOGLE_CREDENTIALS}}" >> .env.production
        working-directory: ${{ github.workspace }}

      - name: Print contents of .env.production file
        run: cat .env.production

  build:
    runs-on: self-hosted

    steps:
      - name: Build
        run: npm run build --if-present
